
from django.contrib import admin
from django.urls import path, include
import views
urlpatterns = [
    path('', views.index, name="index "),
    path('login', views.login , name="login"),
    path('create', views.create , name="create"),
    path('agregar_producto', views.agregar_producto, name="agregar_producto"),
path('banadmin', views.banadmin, name="banadmin"),
path('borrarcuenta', views.borrarcuenta, name="borrarcuenta"),
path('Cactus', views.Cactus, name="Cactus"),
path('Carrito', views.Carrito, name="Carrito"),
path('categorias', views.categorias, name="categorias"),
path('changeforgoh', views.changeforgoh, name="changeforgoh"),
path('chNGE', views.chNGE, name="chNGE"),
path('compra_cactus1', views.compra_cactus1, name="compra_cactus1"),
path('compra_cactus2', views.compra_cactus2, name="compra_cactus2"),
path('compra_cactus3', views.compra_cactus3, name="compra_cactus3"),
path('compra_cactus4', views.compra_cactus4, name="compra_cactus4"),
path('compra_cactus5', views.compra_cactus5, name="compra_cactus5"),
path('compra_cactus6', views.compra_cactus6, name="compra_cactus6"),
path('Compra_fertilizante1', views.Compra_fertilizante1, name="Compra_fertilizante1"),
path('Compra_fertilizante2', views.Compra_fertilizante2, name="Compra_fertilizante2"),
path('Compra_fertilizante3', views.Compra_fertilizante3, name="Compra_fertilizante3"),
path('Compra_fertilizante4', views.Compra_fertilizante4, name="Compra_fertilizante4"),
path('Compra_fertilizante5', views.Compra_fertilizante5, name="Compra_fertilizante5"),
path('Compra_fertilizante6', views.Compra_fertilizante6, name="Compra_fertilizante6"),
path('Compra_maceta1', views.Compra_maceta1, name="Compra_maceta1"),
path('Compra_maceta2', views.Compra_maceta2, name="Compra_maceta2"),
path('Compra_maceta3', views.Compra_maceta3, name="Compra_maceta3"),
path('Compra_maceta4', views.Compra_maceta4, name="Compra_maceta4"),
path('Compra_maceta5', views.Compra_maceta5, name="Compra_maceta5"),
path('Compra_maceta6', views.Compra_maceta6, name="Compra_maceta6"),
path('Compra_Pago', views.Compra_Pago, name="Compra_Pago"),
path('Compra_pesticida1', views.Compra_pesticida1, name="Compra_pesticida1"),
path('Compra_pesticida2', views.Compra_pesticida2, name="Compra_pesticida2"),
path('Compra_pesticida3', views.Compra_pesticida3, name="Compra_pesticida3"),
path('compra_planta1', views.compra_planta1, name="compra_planta1"),
path('Compra_planta2', views.Compra_planta2, name="Compra_planta2"),
path('Compra_planta3', views.Compra_planta3, name="Compra_planta3"),
path('Compra_planta4', views.Compra_planta4, name="Compra_planta4"),
path('Compra_planta5', views.Compra_planta5, name="Compra_planta5"),
path('Compra_planta6', views.Compra_planta6, name="Compra_planta6"),
path('Contacto', views.Contacto, name="Contacto"),
path('editar_producto', views.editar_producto, name="editar_producto"),
path('eliminar_producto', views.eliminar_producto, name="eliminar_producto"),
path('Fertilizante', views.Fertilizante, name="Fertilizante"),
path('Flores', views.Flores, name="Flores"),
path('Maceteros', views.Maceteros, name="Maceteros"),
path('oferta1', views.oferta1, name="oferta1"),
path('oferta2', views.oferta2, name="oferta2"),
path('oferta3', views.oferta3, name="oferta3"),
path('oferta4', views.oferta4, name="oferta4"),
path('oferta5', views.oferta5, name="oferta5"),
path('oferta6', views.oferta6, name="oferta6"),
path('ofertas', views.ofertas, name="ofertas"),
path('Perfil_administrador', views.Perfil_administrador, name="Perfil_administrador"),
path('Pesticidas', views.Pesticidas, name="Pesticidas"),
path('profile', views.profile, name="profile"),

]
