# Generated by Django 4.1.5 on 2023-05-23 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_com', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direc', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=30)),
                ('num', models.CharField(max_length=20)),
                ('codigo_po', models.CharField(max_length=30)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_preg', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_reg', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=20)),
                ('respuesta', models.CharField(max_length=20)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.pregunta')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('f_despacho', models.DateField()),
                ('f_entrega', models.DateField()),
                ('estatus', models.CharField(max_length=200)),
                ('cod_despacho', models.CharField(max_length=40)),
                ('costo_despacho', models.IntegerField()),
                ('comp_despacho', models.CharField(max_length=30)),
                ('total', models.IntegerField()),
                ('carrito', models.CharField(max_length=40)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.direccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.usuario'),
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.region'),
        ),
    ]
