# Generated by Django 4.2.1 on 2023-06-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_usuario_pregunta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comuna",
            name="nombre",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="region",
            name="nombre",
            field=models.CharField(max_length=50),
        ),
    ]
