# Generated by Django 4.2.2 on 2023-06-20 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_comuna_nombre_alter_region_nombre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factura",
            name="carrito",
        ),
        migrations.DeleteModel(
            name="Detalle",
        ),
    ]
