# Generated by Django 4.2.2 on 2023-06-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_remove_factura_carrito_delete_detalle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factura",
            name="f_despacho",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="f_entrega",
        ),
    ]
