# Generated by Django 4.2.2 on 2023-06-20 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_remove_factura_f_despacho_remove_factura_f_entrega"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factura",
            name="cod_despacho",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="comp_despacho",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="costo_despacho",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="direccion",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="estatus",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="fecha_compra",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="id_factura",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="total",
        ),
        migrations.AddField(
            model_name="factura",
            name="direcc",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factura",
                to="menu.direccion",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="factura",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="factura",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facturas",
                to="menu.usuario",
            ),
        ),
    ]
