# Generated by Django 4.2.2 on 2023-06-20 02:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0007_remove_factura_cod_despacho_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factura",
            name="id",
        ),
        migrations.AddField(
            model_name="factura",
            name="estatus",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="factura",
            name="factura",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="factura",
            name="fechacompra",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="factura",
            name="montopagao",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="factura",
            name="pagao",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Detalle",
            fields=[
                ("detalle", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.IntegerField()),
                ("cantidad", models.IntegerField()),
                (
                    "factu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cosas",
                        to="menu.factura",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prod",
                        to="menu.producto",
                    ),
                ),
            ],
        ),
    ]
