# Generated by Django 4.1.5 on 2023-06-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_factura_id_factura_estatus_factura_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cod_despacho',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
