# Generated by Django 4.1.5 on 2023-06-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_factura_cod_despacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cod_despacho',
            field=models.IntegerField(verbose_name=11),
        ),
    ]
