# Generated by Django 4.1.5 on 2023-06-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_remove_factura_cod_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='COD_DESPACHO',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
